/* tables */
DROP TABLE IF EXISTS wcf1_tour;
CREATE TABLE wcf1_tour (
	tourID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	isDisabled TINYINT(1) NOT NULL DEFAULT 0,
	visibleName VARCHAR(255) NOT NULL,
	tourTrigger VARCHAR(255) NOT NULL DEFAULT 'firstSite',
	className VARCHAR(255) NULL DEFAULT NULL,
	tourName VARCHAR(255) NULL DEFAULT NULL,
	
	UNIQUE KEY (tourName)
);

DROP TABLE IF EXISTS wcf1_tour_step;
CREATE TABLE wcf1_tour_step (
	tourStepID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	tourID INT(10) NOT NULL,
	showOrder INT(10) NOT NULL,
	isDisabled TINYINT(1) NOT NULL DEFAULT 0,
	target VARCHAR(255) NOT NULL,
	placement ENUM('top', 'bottom', 'right', 'left') NOT NULL DEFAULT 'right',
	title VARCHAR(255) NOT NULL DEFAULT '',
	content MEDIUMTEXT NOT NULL,
	xOffset INT(10) NOT NULL DEFAULT 0,
	yOffset INT(10) NOT NULL DEFAULT 0,
	showPrevButton TINYINT(1) NOT NULL DEFAULT 1,
	url VARCHAR(255) NULL DEFAULT NULL,
	
	KEY (tourID)
);

DROP TABLE IF EXISTS wcf1_tour_user;
CREATE TABLE wcf1_tour_user (
	tourID INT(10) NOT NULL,
	userID INT(10) NOT NULL,
	
	UNIQUE KEY (tourID, userID),
	KEY (userID)
);

/* foreign keys */
ALTER TABLE wcf1_tour_step ADD FOREIGN KEY (tourID) REFERENCES wcf1_tour (tourID) ON DELETE CASCADE;
ALTER TABLE wcf1_tour_user ADD FOREIGN KEY (tourID) REFERENCES wcf1_tour (tourID) ON DELETE CASCADE;
ALTER TABLE wcf1_tour_user ADD FOREIGN KEY (userID) REFERENCES wcf1_user (userID) ON DELETE CASCADE;
